include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    deprecated_member_use_from_same_package: warning
    invalid_annotation_target: ignore
    missing_return: error
    sdk_version_async_exported_from_core: ignore
    todo: ignore
    unnecessary_null_comparison: warning
    missing_required_param: error
  exclude:
    - android/**
    - ios/**
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart
    - lib/generated/**/*.dart

linter:
  rules:
    always_use_package_imports: true
    omit_local_variable_types: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_constructors_first: true
    sort_pub_dependencies: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_null_checks: true
    unnecessary_statements: true
    use_key_in_widget_constructors: false
